services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
