server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/service_db
  cache:
    type: simple

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
